### ISSUE TITLE
Error with latest neovim update

### ISSUE THREAD

**Issue by flleonx** [phaazon/hop.nvim#213] opened 2022-01-06 02:56 UTC
E5108: Error executing lua ....config/nvim/pack/packer/start/hop.nvim/lua/hop/hint.lua:97: Expected Lua number           
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ....config/nvim/pack/packer/start/hop.nvim/lua/hop/hint.lua:97: in function 'set_hint_extmarks'
        ....config/nvim/pack/packer/start/hop.nvim/lua/hop/init.lua:188: in function 'hint_with_callback'
        ....config/nvim/pack/packer/start/hop.nvim/lua/hop/init.lua:129: in function 'hint_with'
        ....config/nvim/pack/packer/start/hop.nvim/lua/hop/init.lua:276: in function 'hint_words'
        [string ":lua"]:1: in main chunk

nvim --version
neovim-0.7.0~ubuntu1+git202201060048-09d270bce-dd05b3569

**Comment by cj** [comment] 2022-01-07 16:46
I can confirm this error

**Comment by clason** [comment] 2022-01-08 21:29
I have no way of confirming this error since the issue completely lacks any reproducing steps.

**Comment by flleonx** [comment] 2022-01-08 22:08
The following is my configuration. By pressing <leader>ww you can get the error.

`
require'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }

local mapper = function(mode, key, result)
  vim.api.nvim_set_keymap(mode, key, result, { noremap = true, silent = false })
end

-- String statements
local n = "n"

-- Using lua functions
mapper(n, "<leader>ww", "<cmd>lua require'hop'.hint_words({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR })<cr>")
mapper(n, "<leader>bb", "<cmd>lua require'hop'.hint_words({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR })<cr>")
mapper(n, "<leader>ll", "<cmd>lua require'hop'.hint_lines({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR })<cr>")
mapper(n, "<leader>mm", "<cmd>lua require'hop'.hint_lines({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR })<cr>")
`

**Comment by LudoPinelli** [comment] 2022-01-09 01:52
I have this error too.
it happens when triggering the following functions (no matter if some arguments are given or not) in normal and operator pending mode:

- `lua require("hop").hint_char1()` 
- `lua require("hop").hint_char2()` 
 
Strangely (or not I don't know^^), they work fine in visual mode.
_hop_ Line and word modes functions works fine.

**Comment by yashlala** [comment] 2022-01-09 05:31
I'm not able to reproduce this problem under neovim 0.6.1, which looks like it's the latest release. 

Are all of you running unreleased builds (I see a `neovim-0.7.0~ubuntu1+git202201060048-09d270bce-dd05b3569`)?

**Comment by LudoPinelli** [comment] 2022-01-09 05:49
I am, yes.

**Comment by clason** [comment] 2022-01-09 07:27
I cannot reproduce it, and I'm on latest master. Make sure both Neovim _and hop.nvim_ are updated to the latest commit.

**Comment by LudoPinelli** [comment] 2022-01-09 13:45
After more tests, the problem occurs when the `current_line_only` option is set to `true`, wether it is in word mode, 1-char mode or 2-char mode.

The build I have seems slightly ahead of yours now,:
`neovim-0.7.0~ubuntu1+git202201090047-c7ffe406b-dd05b3569`
I ran PackerSync, so hop is updated.

**Comment by clason** [comment] 2022-01-09 14:33
That looks like a duplicate of #214 then (which sounds like a regression introduced by the just-merged big multi-window PR).

**Comment by LudoPinelli** [comment] 2022-01-09 15:54
Yes, I don't for the OP but in my case it is.

**Closed** 2022-01-09 17:08 UTC
