### ISSUE TITLE
case insensitive does not work if first character is non-alpha.

### ISSUE THREAD

**Issue by jdhao** [phaazon/hop.nvim#175] opened 2021-11-05 12:39 UTC
I have already turned of case insensitive search via `  case_insensitive = true,`. However, in HopChar2, if the first character is not alpha, case_insensitive is not respected.

For example, for the following text:

```
"{ Header info
" Description: This is my personal Nvim configuration supporting Mac, Linux
" and Windows, with various plugins configured. This configuration evolves as
" I learn more about Nvim and becomes more proficient in using Nvim. Since it
" is very long (more than 1000 lines!), you should read it carefully and take
" only the settings and options that suits you. I would not recommend cloning
" this repo and replace your own config. Good configurations are personal,
" built over time with a lot of polish.
" Author: Jie-dong Hao
" Email: jdhao@hotmail.com
"}

"{ Main configurations
let g:config_files = [
      \ 'globals.vim',
      \ 'options.vim',
      \ 'autocommands.vim',
      \ 'mappings.vim',
      \ 'plugins.vim',
      \ 'themes.vim'
      \ ]

for s:fname in g:config_files
  execute printf('source %s/core/%s', stdpath('config'), s:fname)
endfor
"}
```

If I run `:HopChar2`, and press <kbd>Space</kbd><kbd>m</kbd>, space before `Main` is not highlighted.

![image](https://user-images.githubusercontent.com/16662357/140511412-de9c130c-9280-4fd2-8741-3bef881b1d3c.png)

**Comment by phaazon** [comment] 2021-11-05 19:17
Probably a duplicate of #74.

**Closed by phaazon** 2021-11-05 19:17 UTC
