### ISSUE TITLE
Jump to line and keep column?

### ISSUE THREAD

**Issue by aprowe** [phaazon/hop.nvim#219] opened 2022-01-18 21:52 UTC
Hello, loving the plugin. One thing that seems to be missing from easy motion is the ability to jump to a line and keep the column that you are in. I didn't see any commands or options for it in the config. 
Am I missing it somewhere or this a feature that needs to be added?

**Comment by phaazon** [comment] 2022-01-19 15:57
Duplicate of #125.

**Closed by phaazon** 2022-01-19 15:57 UTC
