### ISSUE TITLE
Motions jump one cell too far

### ISSUE THREAD

**Issue by runiq** [phaazon/hop.nvim#192] opened 2021-11-22 07:26 UTC
Hi, long time no see, still a big fan :)

I believe there might be a bug with cursor positioning  and the`inclusive_jump` setting. When I do `hop_char1()` with the default setting of `inclusive_jump = false`, I jump right on top of the matched letter, which is consistent with the `f` motion (not with the `t` motion as stated in the docs).

Just to be sure, I tried `hop_char1()` with `inclusive_jump = true` and the motion puts my cursor just after the matched character. So the behavior is consistent, at least. :)

Am I misunderstanding something about `inclusive_jump`'s intended behavior? I thought the docs and your recent hop 1.1 announcement made things pretty clear, but the behavior didn't match up with my intuition.

**Comment by clason** [comment] 2021-11-22 09:07
Duplicate of #191? (The `inclusive_jump` was initially meant for operator mode only.)

**Comment by phaazon** [comment] 2021-11-22 09:20
The name of the feature is misleading indeed. I will probably switch to the other design I had intended first (`offset`), so that every possibility can be implemented (in operator-pending mode, but also any other mode).

**Closed** 2021-11-22 09:20 UTC
