### ISSUE TITLE
Error when using `t` hop to first character in line

### ISSUE THREAD

**Issue by shyun3** [phaazon/hop.nvim#283] opened 2022-07-16 01:03 UTC
Using this `t` mapping:
```lua
vim.api.nvim_set_keymap('', 't', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, hint_offset = -1 })<cr>", {})
```
the following error occurs when hopping to a character in the first column:
```
E5108: Error executing lua /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:279: Column value outside range
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:279: in function 'move_cursor_to'
        /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:288: in function 'callback'
        /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:392: in function 'refine_hints'
        /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:354: in function 'hint_with_callback'
        /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:287: in function 'hint_with'
        /home/mhyun/.config/nvim/bundle/hop.nvim/lua/hop/init.lua:474: in function 'hint_char1'
        [string ":lua"]:1: in main chunk
```

To reproduce:
```
hello
world
```
place the cursor anywhere on the first line of this snippet, then use the `t` mapping to jump to the "w" on the 2nd line.

**Comment by phaazon** [comment] 2022-07-21 21:06
Duplicate of #261, it’s the same issue.

**Closed by phaazon** 2022-07-21 21:06 UTC
